### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [dajwill/helper_practice#1]
A couple issues here. First, you only removed `:pending` without also removing the preceding comma, which is making all the specs fail to run. Once you fix that though, you should still see these spec failures:

```
Failures:

  1) MethodsPracticeHelpers#current_date_and_time returns the properly formatted date and time for February 14, 2015 at 7:27pm
     Failure/Error: expect(current_date_and_time).to eq('February 14, 2015 at 7:27pm')

       expected: "February 14, 2015 at 7:27pm"
            got: "February, 2015 at 07:27PM"

       (compared using ==)
     # ./spec/helpers/methods_practice_helpers/current_date_and_time_spec.rb:15:in `block (3 levels) in <top (required)>'

  2) MethodsPracticeHelpers#current_date_and_time returns the properly formatted date and time for May 6, 2008 at 1:56am
     Failure/Error: expect(current_date_and_time).to eq('May 6, 2008 at 1:56am')

       expected: "May 6, 2008 at 1:56am"
            got: "May, 2008 at 01:56AM"

       (compared using ==)
     # ./spec/helpers/methods_practice_helpers/current_date_and_time_spec.rb:25:in `block (3 levels) in <top (required)>'
```

Please fix these. If you get stuck and aren't sure what to do, let me know and I'll be happy to point you in the right direction.

**Comment by dajwill** [comment]
Hi Chris,

I the time should now be displaying the date.

**Comment by chrisvfritz** [comment]
This is better, but still isn't *quite* right. The specs are now running correctly though, so if you run `bundle exec rspec`, you'll be able see exactly where the return of your code and what the program is expecting isn't matching up.

**Comment by dajwill** [comment]
It finally passes all the test.

**Comment by chrisvfritz** [comment]
:+1: Looks much better!
